development:
  adapter: postgresql
  encoding: unicode
  database: cipher
  pool: 5
  username: root
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: cipher
  pool: 5
  username: root
  password: 

production: 
  adapter: postgresql
  encoding: unicode
  username: username
  port: 5432
  host: hostname
  database: database
  password: password
