development:
  adapter: postgresql
  encoding: unicode
  database: cipher
  pool: 5
  username: root
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: cipher
  pool: 5
  username: root
  password: 

production:
  url: <%= ENV['DATABASE_URL'] %>
